### ISSUE TITLE
Socket closed

### ISSUE THREAD

**Issue by PunKeel** [par0noid/ts3admin.class#3]
Hello,

There is no support if the socket is closed: the while loops becomes an infinite loop here: https://github.com/par0noid/ts3admin.class/blob/master/lib/ts3admin.class.php#L4211

What about adding *basic* support for detecting dead sockets?

Thx! :)

**Comment by par0noid** [comment]
Hey PunKeel,

thanks for your message.

I'll take a look at this the next days :) code suggestions welcome

Best regards
Stefan

**Comment by par0noid** [comment]
I'm still trying to find a solution for detecting death connections. Mabye @Viper61 could help? 😆

**Comment by par0noid** [comment]
Currently I have no idea how to solve this :(

**Comment by Nik99** [comment]
I found this function here, i dont know if it can help you @par0noid
http://php.net/manual/en/function.socket-get-status.php

**Comment by toxiicdev** [comment]
@par0noid Just try to send a packet to check if socket is alive 👍

**Comment by TheVaan** [comment]
I think @toxiicdev s idea is a good way. Or you can do a socket_get_status() and check if the socket is open/connected.
The link above dosn't show to the correct line anymore... which is the correct line now?

**Comment by toxiicdev** [comment]
@TheVaan Yea I think that socket_get_status() would be a better solution, but we should be sure that it works properly.

**Comment by toxiicdev** [comment]
@par0noid You could try this:

function IsSocketAlive($socket)
{
return @socket_read($socket, 0);
}

**Comment by toxiicdev** [comment]
@everyone Take a look here: https://github.com/par0noid/ts3admin.class/pull/8

**Comment by par0noid** [comment]
Thank you guys, especially @toxiicdev for your help! Version 1.0.1.3 is out now with your bugfix. Together we can achieve anything! ♥

**Comment by MINORITYmaN** [comment]
hi there,
if a deamon is connected to the socket and the server shuts down, cpu jumps to 100%.
this happens if a command is issued or if the destructor is called which calls logout.
imho this should have a detection too.

i made a imho ugly workaround, have 2 different ways for it:

1. using a custom function including `Closure::bind`
2. using `ReflectionClass` including `ReflectionProperty::getValue` and `setAccessible`

both do the same, the give me the chance to access the runtime property to reach the socket.

- during main loop of the deamon before the commands i have to make a new socket connection to check if the query port is listening, if negative then i access the private runtime socket and close it.
- after that  i set the ts3admin class to NULL, and loop until the port gets open again to let the deamon log in to do his job.

this operation is necessary cuz the socket session will be invalid if the server comes up again.

imho, the class could have a property/var which switches when the socket state changes from online to offline without having to build workarounds like the 2 i wrote before.

a deamon could just access this property to know if its allowed to run commands or do other operations (for example try to reconnect, sent to a website/db a info that the server went offline).

perhaps some of you have a better way to get it done without manipulating the main class.


let me know what you think about.
kind regards, stefano
